//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AVTOBAZA
{
    using System;
    using System.Collections.Generic;
    
    public partial class activeZayavki
    {
        public int IdZayavki { get; set; }
        public string FIOzakazchika { get; set; }
        public int TelephoneNumberZakazchika { get; set; }
        public string CarType { get; set; }
        public string Start { get; set; }
        public string Finish { get; set; }
        public int CountPasazhirov { get; set; }
        public int MassaGruza { get; set; }
    }
}
