//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AVTOBAZA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AvtobazaEntities : DbContext
    {
        private static AvtobazaEntities _context;

        public AvtobazaEntities()
            : base("name=AvtobazaEntities")
        {
        }

        public static AvtobazaEntities GetContext()
        {
            if (_context == null)
                _context = new AvtobazaEntities();

            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<avtorizacia> avtorizacia { get; set; }
        public virtual DbSet<CatType> CatType { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Zayavka> Zayavka { get; set; }
        public virtual DbSet<activeZayavki> activeZayavki { get; set; }
    }
}
